name: multisuperstore
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1+2

environment:
  sdk: ">=2.7.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 0.1.2
  mvc_pattern: 6.3.0
  global_configuration: ^2.0.0-nullsafety.1
  http: ^0.13.3
  html: 0.14.0+3
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  flutter_svg: 0.22.0
  toast: ^0.1.5
  flutter_staggered_grid_view: 0.3.2
  speech_to_text_platform_interface: ^2.0.0
  #intl_utils: 1.6.3
  firebase_core:
  firebase_auth:

  flutter_facebook_auth: ^3.5.7
  google_sign_in:
  flutter_swiper: ^1.1.6
  carousel_slider: 2.2.1
  auto_size_text: ^2.1.0
  simple_animations: ^1.3.3
  rflutter_alert: ^1.0.3
  flutter_rating_bar: 3.2.0+1
  sliding_up_panel: ^1.0.2
  getwidget: 1.2.4
  flare_flutter: ^2.0.6
  otp_text_field: ^1.0.1
  percent_indicator: ^2.1.7+2
  smooth_star_rating: ^1.0.3
  like_button: 1.0.4
  badges: ^1.1.6
  cached_network_image: 3.0.0
  firebase_messaging: 10.0.3
  firebase_core_platform_interface: ^4.0.1
  plugin_platform_interface: ^2.0.0
  google_maps_flutter: 2.0.6
  geocoding: ^2.0.1
  geolocator: ^6.1.14
  flutter_plugin_android_lifecycle: ^2.0.2
  google_map_location_picker: ^4.1.7
  place_picker: ^0.9.18
  speech_to_text: ^4.2.1
  avatar_glow: ^1.2.0
  razorpay_flutter: ^1.2.5
  responsive_ui:
  cloud_firestore: ^2.1.0
  timeline_tile:
  date_format: ^2.0.2
  flutter_polyline_points:
  dio:
  date_picker_timeline: ^1.2.3
  circular_countdown_timer: ^0.0.1
  intro_views_flutter: ^2.8.0
  flutter_local_notifications: ^6.0.0
  after_layout: ^1.1.0
  keyboard_actions: 3.4.3
  just_audio:
  upi_india: 3.0.1
  webview_flutter: ^2.0.12
  convex_bottom_bar: ^3.0.0
  location: ^4.3.0
  shimmer_animation: ^2.1.0+1
  url_launcher:
  flutter_google_places: ^0.3.0
  shimmer: ^2.0.0
  image_picker:
  flutter_barcode_scanner: ^2.0.0
  intl: ^0.17.0
  video_player: ^2.2.4
  
  









dependency_overrides:
  intl: 0.17.0
  geolocator_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cfg/
    - assets/img/
    - assets/audio/
    - assets/video/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Futura-Book-Regular
      fonts:
        - asset: assets/fonts/Futura-Book-Regular.ttf
          weight: 100
    - family: Touche W03 Regular
      fonts:
        - asset: assets/fonts/Touche W03 Regular.ttf
          weight: 100
    - family: Touche W03 Light
      fonts:
        - asset: assets/fonts/Touche W03 Light.ttf
          weight: 100
    - family: Touche W03 Bold
      fonts:
        - asset: assets/fonts/Touche W03 Bold.ttf
          weight: 100
    - family: Touche W03 Semibold
      fonts:
        - asset: assets/fonts/Touche W03 Semibold.ttf
          weight: 500
    - family: Touche W03 Medium
      fonts:
        - asset: assets/fonts/Touche W03 Medium.ttf
          weight: 500

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
